### ISSUE TITLE
How to avoid exporting huge data to future workers by using progressr

### ISSUE THREAD

**Issue by marcus-eger** [HenrikBengtsson/progressr#116] opened 2021-07-09 15:04 UTC
The progressr function defined in the code before parallelization such as
`p <- progressr::progressor(along=data)`
exports the current environment (incl. data) to the workers when p is given as argument to future_mapply. This can lead to huge (unexpected) memory consumption. The memory exported is revealed by serializing the function p. How can this be avoided?
Thx a lot, Marcus

Full code example:
```
workerFunc <- function(x, p) {
	p()
	sqrt(x)
}

myFunc <- function(n) {
	data <- abs(rnorm(n))
	p <- progressr::progressor(along=data)
	print(length(serialize(p, NULL)))
	#future.apply::future_mapply(workerFunc, data, MoreArgs=list(p))
}
```

```
> myFunc(1)
[1] 5162
> myFunc(10000)
[1] 165146
```

**Comment by HenrikBengtsson** [comment] 2021-07-09 15:15
Thank you for this report and troubleshooting.  This is a really good point.  It can probably be solved by the package itself, but until a new version is available, I think one should be able to come up with a temporary workaround.  I'll try to come up with something.

**Comment by HenrikBengtsson** [comment] 2021-07-12 07:42
I think I've fixed this in commit 8c1f7232. Please try with progressr (>= 0.8.0-9001):

```r
remotes::install_github("HenrikBengtsson/progressr", ref="develop")
```

**Comment by marcus-eger** [comment] 2021-07-12 07:42
A simple but not so beautiful workaround is to address lexical scoping by wrapping the `progressor()` call in a global function
```
progressFunc <- function(steps) {
	progressr::progressor(along=1:steps)
}
```
of course, without providing the data object itself, only its length, as argument:
```
myFunc <- function(n) {
	data <- abs(rnorm(n))
	p <- progressFunc(length(data))
	print(length(serialize(p, NULL)))
	#future.apply::future_mapply(workerFunc, data, MoreArgs=list(p))
}
```

**Comment by marcus-eger** [comment] 2021-07-12 07:51
Your commit works for me and does not inflate the progressr function.

**Comment by HenrikBengtsson** [comment] 2021-07-12 07:57
Great. Thanks for confirming.

**Comment by marcus-eger** [comment] 2021-07-12 07:59
. and thanks a lot for responding so rapidly!

Regards

Marcus

 

Von: Henrik Bengtsson ***@***.***> 
Gesendet: Montag, 12. Juli 2021 09:58
An: HenrikBengtsson/progressr ***@***.***>
Cc: Eger, Marcus ***@***.***>; Author
***@***.***>
Betreff: Re: [HenrikBengtsson/progressr] How to avoid exporting huge data to
future workers by using progressr (#116)

 

Great. Thanks for confirming.

-
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.co
m%2FHenrikBengtsson%2Fprogressr%2Fissues%2F116%23issuecomment-878058842&data
=04%7C01%7Cmarcus.eger%40draeger.com%7Cc02b84d85f6b4ed4e67f08d9450ac85a%7Ce8
d897a8f4004625858a6f3ae627542b%7C1%7C0%7C637616734877376502%7CUnknown%7CTWFp
bGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7
C1000&sdata=PtVMksi%2FrSgwrmd0rRsukoD99wQUDUHFsY0t7rGxce0%3D&reserved=0> ,
or unsubscribe
<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.co
m%2Fnotifications%2Funsubscribe-auth%2FAUZHQJE7ZBTYPYV4RQKEAGLTXKOA3ANCNFSM5
AC55QSA&data=04%7C01%7Cmarcus.eger%40draeger.com%7Cc02b84d85f6b4ed4e67f08d94
50ac85a%7Ce8d897a8f4004625858a6f3ae627542b%7C1%7C0%7C637616734877386497%7CUn
known%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJX
VCI6Mn0%3D%7C1000&sdata=%2FssGGP%2FHhXpyldjva0S632GQ%2FcgBFktN5NhdgcgSsgw%3D
&reserved=0> .

**Comment by marcus-eger** [comment] 2021-07-12 09:20
A short feedback on using the fix: 

the worker's memory is not inflated, but for some reason, the memory
consumption of the main R process increases enormously. This also happens if
the progressor is wrapped in a global function. 

 

I did not have the opportunity to further investigate this / reproduce with
a small example.

 

Kind regards

            Marcus 

 

 

Von: Henrik Bengtsson ***@***.***> 
Gesendet: Montag, 12. Juli 2021 09:43
An: HenrikBengtsson/progressr ***@***.***>
Cc: Eger, Marcus ***@***.***>; Author
***@***.***>
Betreff: Re: [HenrikBengtsson/progressr] How to avoid exporting huge data to
future workers by using progressr (#116)

 

I think I've fixed this in commit
<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.co
m%2FHenrikBengtsson%2Fprogressr%2Fcommit%2F8c1f7232300d67f097a86335dc543f9a8
fc2d9f0&data=04%7C01%7Cmarcus.eger%40draeger.com%7Cf2a40ca6987b40e1d5af08d94
5089f96%7Ce8d897a8f4004625858a6f3ae627542b%7C1%7C0%7C637616725638053493%7CUn
known%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJX
VCI6Mn0%3D%7C1000&sdata=yfDH%2FoqVe561v9rMBUmyQdxl45Crt0EDEyg5Vt1FKkU%3D&res
erved=0> 8c1f723. Please try with progressr (>= 0.8.0-9001):

remotes::install_github("HenrikBengtsson/progressr", ref="develop")

-
You are receiving this because you authored the thread.
Reply to this email directly,
<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.co
m%2FHenrikBengtsson%2Fprogressr%2Fissues%2F116%23issuecomment-878049832&data
=04%7C01%7Cmarcus.eger%40draeger.com%7Cf2a40ca6987b40e1d5af08d945089f96%7Ce8
d897a8f4004625858a6f3ae627542b%7C1%7C0%7C637616725638053493%7CUnknown%7CTWFp
bGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7
C1000&sdata=D0rlYLL%2BEk53r5dvu8zZQZS15Om5agE15O2VN%2FcH6yU%3D&reserved=0>
view it on GitHub, or
<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.co
m%2Fnotifications%2Funsubscribe-auth%2FAUZHQJB6HZ22SBQUJYW2V3LTXKMG3ANCNFSM5
AC55QSA&data=04%7C01%7Cmarcus.eger%40draeger.com%7Cf2a40ca6987b40e1d5af08d94
5089f96%7Ce8d897a8f4004625858a6f3ae627542b%7C1%7C0%7C637616725638063490%7CUn
known%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJX
VCI6Mn0%3D%7C1000&sdata=X2QcwKjIi7AGFVa4yM8G8I%2BmIEz9fz%2BLN9Y737OuVXI%3D&r
eserved=0> unsubscribe.

**Comment by HenrikBengtsson** [comment] 2021-07-12 09:42
Hmm...  can you please share your `sessionInfo()`?

**Comment by marcus-eger** [comment] 2021-07-12 11:40
I seem to have been able to reproduce the behaviour with this small example:

```
workerFunc <- function(x, p, ...) {
	p(message = sprintf("x=%g", x))
	sqrt(...)
}

myFunc <- function(n) {
	data <- abs(rnorm(n))
	p <- progressr::progressor(steps = n)
	res = future.apply::future_mapply(workerFunc, x = seq_along(data), data, MoreArgs = list(p = p))
}

progressr::handlers(global = TRUE)
progressr::handlers("progress")
future::plan("sequential")
#future::plan("multisession", workers=4)

myFunc(1e4)
```

Starting with empty plain R Console the amount of memory consumed rises monotonously with the progression. At the end, the memory consumption is fixed, `gc()` does not change anything. However, `mem_used()` is low. I tested "multisession" and "sequential", see below.

`future::plan("multisession", workers=4)`

```
R> pryr::mem_used()
44 MB
```
Task manager: 
R for Windows GUI front-end **5138.6 MB**
    4 x
    R for Windows front-end 66.3 MB

`future::plan("sequential")`

```
R> pryr::mem_used()
42.4 MB
```
Task manager:
R for Windows GUI front-end  **253.8 MB**


```
R> sessionInfo()
R version 4.0.3 (2020-10-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19042)

Matrix products: default

Random number generation:
 RNG:     Mersenne-Twister 
 Normal:  Inversion 
 Sample:  Rounding 
 
locale:
[1] LC_COLLATE=German_Germany.1252  LC_CTYPE=German_Germany.1252    LC_MONETARY=German_Germany.1252 LC_NUMERIC=C                    LC_TIME=German_Germany.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.6           progressr_0.8.0-9001 codetools_0.2-18     listenv_0.8.0        prettyunits_1.1.1    future_1.21.0        digest_0.6.27       
 [8] crayon_1.4.1         parallelly_1.26.0    R6_2.5.0             lifecycle_1.0.0      magrittr_2.0.1       stringi_1.6.2        future.apply_1.7.0  
[15] rlang_0.4.11         progress_1.2.2       pryr_0.1.4           vctrs_0.3.8          ellipsis_0.3.2       tools_4.0.3          stringr_1.4.0       
[22] hms_1.1.0            parallel_4.0.3       compiler_4.0.3       pkgconfig_2.0.3      globals_0.14.0 
```

**Comment by HenrikBengtsson** [comment] 2021-09-22 19:29
> A short feedback on using the fix:
> 
> the worker's memory is not inflated, but for some reason, the memory
> consumption of the main R process increases enormously. ...

I've been trying to reproduce this, that is, to see if there was a regression from **progressr** 0.8.0 and 0.8.0-9001 ("the fix"), but I cannot see any difference here.  So, are you sure what you're now observing wasn't there before "the fix"?

Can you please try with:

```r
library(progressr)
handlers(global = TRUE)
future::plan("cluster", workers = 1L)

workerFunc <- function(x, p) {
  p()
  sqrt(x)
}

myFunc <- function(n) {
  data <- abs(rnorm(n))
  p <- progressr::progressor(along=data)
  print(length(serialize(p, NULL)))
  future.apply::future_mapply(workerFunc, data, MoreArgs=list(p))
}

for (kk in 1:100) y <- myFunc(1000)
```

with both **progressr** 0.8.0 (CRAN) and **progressr** 0.8.0-9001 (GitHub)?

I removed `handlers("progress")` to rule out that package.  I also use a single background worker instead of four, to create a minimal setup.

**Comment by HenrikBengtsson** [comment] 2021-09-24 00:26
I've figured out the second problem.  The culprit is that each progression condition signaled also carry the recorded call stack, which can blow up a single progress update object 100 times (5 kB to 500 kB).  Now, since futures record all conditions, that means that if you signal 1000 progress updates, then the future will occupy 500 MB, which mostly contain identical call stacks.  In progressr (>= [0.8.0-9005](https://github.com/HenrikBengtsson/progressr/commit/3c9277eb55fd79c904dfbde3add35022838dfe23)), I've disabled the collection of call stacks, so now that future will only occupy 5 MB (=1000 * 5kB).

Try with:

```r
remotes::install_github("HenrikBengtsson/progressr", ref = "develop")
```

I'm closing.  Please let me know if you still are observing issues related to this.

**Closed by HenrikBengtsson** 2021-09-24 00:26 UTC
Labels: bug, enhancement, bug/large-overhead-with-large-objects

**Comment by marcus-eger** [comment] 2021-09-24 06:53
Thanks a lot, I will try as you propose - and if I observe issues, let you know. Not sure whether I can make it today ...

**Comment by marcus-eger** [comment] 2021-09-24 09:29
I checked the fix in my environment, seems to work fine! Memory consumption is not monotonously rising, anymore, but fixed and acceptable in size. Thanks a lot.

**Comment by HenrikBengtsson** [comment] 2021-09-24 11:49
Thanks for confirming. I'll start working on getting the next release out on CRAN.

**Comment by HenrikBengtsson** [comment] 2021-09-24 14:31
progressr 0.9.0 is now on CRAN.
