### ISSUE TITLE
Sequential Loop inside of future.apply - progressing the progress bar

### ISSUE THREAD

**Issue by erichare** [HenrikBengtsson/progressr#66] opened 2019-10-19 15:03 UTC
First of all, thank you so much for the fantastic progressr and future.apply packages. It's opening a whole new world to me. But admittedly I'm very new to it, and a little confused about one thing. I'm not sure its an issue so much as me not understanding, so apologies if this isn't the right venue. 

Suppose I have an outer `future_lapply` call, which performs a task in parallel over the number of cores available on the machine. Within that, I have a sequential for loop, in which I want to increment progress. Here's a minimal example:

```
library(future.apply)
plan(multisession, workers = 4)
library(progressr)

y <- with_progress({
    p <- progressor(400L)
    future_lapply(1:4, FUN = function(i) {
        for (i in 1:100) {
            p()
            Sys.sleep(0.25)
        }
    })
})
```
I can replace the `future_lapply` with `lapply` and I get the progress updates immediately, each iteration of the loop. Is there any way to get the updates right away, as available, from each individual worker process in `future_lapply`?

**Comment by HenrikBengtsson** [comment] 2019-10-23 00:17
Hi. Yes, this is currently the expected behavior when using the `multisession` backend, and most other backends as they are implemented right now.  So, this is what happens.   You have four (4) workers, which are all running their own R process in the backround.  You `future_lapply(1:4, ...)` call will cause the following expression:
```r
        for (i in 1:100) {
            p()
            Sys.sleep(0.25)
        }
```
to be evaluated in each of those background R processes.  So far so good.  Now, each call to `p()` signals a progression update (formally a condition in R).  These are relayed to the main R process (the one that listens and report on progression updates with `with_progress()`) _only when_ all of that expression is completed.

Basically each iteration will gather 100 progression updates (from `p()` calls) and then burst relay all of them when done (increasing the progress 25% - but if you could slow it down, you'd see it would go 1%, 2%, ..., 25%, and so on).  What complicates it further is that the default is to clear the progress bar when done, so, if all four `future_lapply()` iteration finish at the same times then you might only see the updates flash by before the progress bar disappears.  If you use:
```r
handlers(txtprogressbar_handler(clear=FALSE))
```
it will not be cleared afterward.

I understand that you expect each progression update to be relayed instantly ("live") from the background worker to the main R session as soon as you call `p()`.  This is not supported by any parallel backends right now.  However, I am working on a prototype for `multisession` (a PSOCK cluster) that will relay progression updates almost instantly.  

To further clarify, when you use `plan(sequential)`, or `lapply()` as you say, then you will indeed see that each `p()` is reported on immediately.  This is because those progression updates are signaled within the same R process that listens to them (via `with_progress()`).

Hope this helps

**Comment by HenrikBengtsson** [comment] 2020-05-06 23:25
Closing. These days, multisession and cluster future backends support near-live progress updates. This is now clarified in the vignette (next release) and the README.

**Closed by HenrikBengtsson** 2020-05-06 23:25 UTC
