### ISSUE TITLE
progress still not reported with Rscript

### ISSUE THREAD

**Issue by randomgambit** [HenrikBengtsson/progressr#88] opened 2020-09-23 19:28 UTC
Hi @HenrikBengtsson thanks again for another masterpiece!
I saw the previous https://github.com/HenrikBengtsson/progressr/issues/77 but I am still not able to get the notifications with `furrr` and `progressr`.

See the example below. Is this expected?

Thanks!

```
library(tidyverse)
library(furrr)
library(progressr)
plan(multicore)

cars <- mtcars %>%
  group_by(carb) %>%
  group_nest()

model_fn <- function(data, p) {
  Sys.sleep(5)
  mod <- lm(mpg ~ cyl + disp, data = data)
  out <- mod$coef
  
  p()
  
  out
}

with_progress({
  p <- progressor(steps = nrow(cars))
  
  cars2 <- cars %>%
    mutate(mod = future_map(data, model_fn, p = p))
}, enable = TRUE, delay_stdout=TRUE)
```

Running `Rscript mycode.R` in the linux terminal works but does show the progress bar.

**Comment by HenrikBengtsson** [comment] 2020-09-23 20:48
> ... Is this expected?

Yes.  This was implicit from Section ['Near-live versus buffered progress updates with futures'](https://github.com/HenrikBengtsson/progressr#near-live-versus-buffered-progress-updates-with-futures) in the README and the vignette.

Since this is more or less a FAQ, I've now updated that section to explicitly list 'multicore' as a yet-to-be-supported backend:

(*) Other future backends, including [`multicore`](https://github.com/HenrikBengtsson/future/issues/419), may gain support for "near-live" progress updating later. Adding support for those is independent of the progressr package. Feature requests for adding that support should go to those future-backend packages.

Note that link to the issue explaining "why".

**Comment by randomgambit** [comment] 2020-09-23 20:50
thanks @HenrikBengtsson it turns out the only way to make it work is to use the environment variable (as suggested in the current docs). Using the `enable=TRUE` argument without the env variable does not work for me.

Thanks!

**Comment by HenrikBengtsson** [comment] 2020-09-23 20:56
I must have misunderstood your question.  So, note that your progress updates will only be flushed from the worker when a future (=a `future_map()` chunk) completes when using `multicore` - you will not get near-live updates while a chunk is still being processed.  That is what I thought the problem was.

**Comment by randomgambit** [comment] 2020-09-23 20:59
that's an interesting point as well :)

**Comment by HenrikBengtsson** [comment] 2020-09-24 01:04
> Using the enable=TRUE argument without the env variable does not work for me.

Oh, I missed this - too much multitasking on my end. This is a bug.

**Comment by HenrikBengtsson** [comment] 2020-09-24 01:59
This has been fixed in the develop branch.

A simplified reproducible example of this problem was to use:

```r
library(progressr)

with_progress({
  p <- progressor(steps = 10)
  sum <- 0
  for (kk in 1:10) {
    Sys.sleep(0.2)
    sum <- sum + kk
    p()
  }
  sum
}, enable = TRUE)
```

**Closed** 2020-09-24 01:58 UTC
Labels: bug, question
